export const ADD_CAMPSITES = "ADD_CAMPSITES";
<<<<<<< HEAD
export const ADD_COMMENTS = "ADD_COMMENTS";
export const COMMENTS_FAILED = "COMMENTS_FAILED";
export const PROMOTIONS_LOADING = "PROMOTIONS_LOADING";
export const ADD_PROMOTIONS = "ADD_PROMOTIONS";
export const PROMOTIONS_FAILED = "PROMOTIONS_FAILED";
=======
export const CAMPSITES_LOADING = "CAMPSITES_LOADING";
export const CAMPSITES_FAILED = "CAMPSITES_FAILED";

export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENTS = "ADD_COMMENTS";
export const COMMENTS_FAILED = "COMMENTS_FAILED";

export const ADD_PROMOTIONS = "ADD_PROMOTIONS";
export const PROMOTIONS_LOADING = "PROMOTIONS_LOADING";
export const PROMOTIONS_FAILED = "PROMOTIONS_FAILED";

export const ADD_PARTNERS = "ADD_PARTNERS";
export const PARTNERS_LOADING = "PARTNERS_LOADING";
export const PARTNERS_FAILED = "PARTNERS_FAILED";
>>>>>>> 61d0f039577f0f4ea7a9f6b99182332608d2766a
